language: python
sudo: required

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

services:
    - docker

before_install:
    - docker-compose -f .travis/docker-compose-travis.yml up -d

matrix:
  include:
    - python: 3.5
      env: TARGETS="test"
      after_success:
        - pip3 install -U codecov
        - codecov
    - python: 3.8
      env: TARGETS="PYTHON_VERSION=py38 test"
      after_success:
        - pip3 install -U codecov
        - codecov
    - python: 3.5
      envs: TARGETS="quality"

install:
    - docker exec ecomworker bash -c "
      sudo apt update -y;
      sudo apt install python3-dev -y;
       "

script:
    - docker exec ecomworker bash -c "cd /edx/app/ecomworker/ecomworker &&
      make $TARGETS"

deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: "$TARGETS = quality"
  password:
    secure: iYAqXv3vygmnv0ns8jQv0ECclJ1NWj1mjlVYNJsTaEnGmdPifUodr7hTyh/vftYRUtQi1CCWJXF8BEcGuYhahhyWrhkW6R/awArnDooF3gcVzZ9Yn8Zt7zXXRZpgbzXX+1HRUr6WeYoO5S+mXKknORD6bClLYwxKP7sJ1XESmq6Q+WNexb1g3F+AHUXihTJmpGptvZ6rRXIQc+NeozooDKLAgLnyOISGhTyXO3f9DJ8KJmj9QstTDyDutcYsDUN0c6stXk7w0Xr5ErobGXsgUKyadIQ44OgwCsyojh8b454rQOc9C2R1FAaoUAdCsJMJ0ZX1u4d6Tn3/lh2BMWdbLia02mRkW8Y13dg0MvObHOClwG+ElN7/9oW6oK3dHXO1Qstd+z5P/i8rufXlB0fqgmfL5aYz5G2kcUVTg0nyV0Cpn0zelLyCQ2rKpbpMoZJEQGBDBc8MR8uP05pH48TXfqRVOK9x8luKX5PSDXME2u6TLAgBo1Kzcbotlj+YDKtBi6F4Vcl1BsYI4lTM+XelL30xcsmZLi66sxAvpaxAhzpqRrw+4qurUkw9Qd5QDZaP0nwM7V0Cg8MZmRpOSZf4bMB65ba0zmg/DfODoE/e/VXfkonKANbOWFYX5twAX7rsd0Hnyf5YuYF68B3V0OCx/lQCQIwJPRYk3FkPCyMubdM=
